export default [
  {
    name: "SanDisk Ultra 128GB SDXC UHS-I Memory Card up to 80MB/s",
    price: 45.89,
    description: "Ultra-fast SD card for cameras and camcorders.",
    ratings: 4.5,
    images: [
      { public_id: "shopit/products/demo/u0u5mx7ofp8drzi5yjjt", url: "http://res.cloudinary.com/udemy-courses/image/upload/v1689961646/shopit/products/demo/u0u5mx7ofp8drzi5yjjt.jpg" },
    ],
    category: "Electronics",
    seller: "SanDisk",
    stock: 1,
    numOfReviews: 12,
    reviews: [],
  },
  {
    name: "Men's Classic Denim Jacket",
    price: 59.99,
    description: "Stylish denim jacket for all seasons.",
    ratings: 4.2,
    images: [
      { public_id: "shopit/products/demo/denimjacket", url: "https://res.cloudinary.com/udemy-courses/image/upload/v1689961801/shopit/products/demo/denimjacket.jpg" },
    ],
    category: "Clothing",
    seller: "Levi's",
    stock: 10,
    numOfReviews: 8,
    reviews: [],
  },
  {
    name: "Nike Air Max 270",
    price: 120.00,
    description: "Comfortable and stylish running shoes.",
    ratings: 4.7,
    images: [
      { public_id: "shopit/products/demo/airmax270", url: "https://res.cloudinary.com/udemy-courses/image/upload/v1689961811/shopit/products/demo/airmax270.jpg" },
    ],
    category: "Footwear",
    seller: "Nike",
    stock: 15,
    numOfReviews: 20,
    reviews: [],
  },
  {
    name: "Logitech MX Master 3 Mouse",
    price: 99.99,
    description: "Ergonomic wireless mouse for productivity.",
    ratings: 4.6,
    images: [
      { public_id: "shopit/products/demo/mxmaster3", url: "https://res.cloudinary.com/udemy-courses/image/upload/v1689961821/shopit/products/demo/mxmaster3.jpg" },
    ],
    category: "Accessories",
    seller: "Logitech",
    stock: 25,
    numOfReviews: 17,
    reviews: [],
  },
  {
    name: "Philips Air Fryer XXL",
    price: 199.99,
    description: "Healthy frying with little or no oil.",
    ratings: 4.4,
    images: [
      { public_id: "shopit/products/demo/airfryer", url: "https://res.cloudinary.com/udemy-courses/image/upload/v1689961831/shopit/products/demo/airfryer.jpg" },
    ],
    category: "Home Appliances",
    seller: "Philips",
    stock: 7,
    numOfReviews: 13,
    reviews: [],
  },
  {
    name: "Atomic Habits by James Clear",
    price: 18.99,
    description: "A book on building good habits and breaking bad ones.",
    ratings: 4.8,
    images: [
      { public_id: "shopit/products/demo/atomichabits", url: "https://res.cloudinary.com/udemy-courses/image/upload/v1689961841/shopit/products/demo/atomichabits.jpg" },
    ],
    category: "Books",
    seller: "Penguin",
    stock: 30,
    numOfReviews: 25,
    reviews: [],
  },
  {
    name: "Maybelline Fit Me Matte Foundation",
    price: 12.99,
    description: "Matte foundation for a flawless look.",
    ratings: 4.3,
    images: [
      { public_id: "shopit/products/demo/maybellinefitme", url: "https://res.cloudinary.com/udemy-courses/image/upload/v1689961851/shopit/products/demo/maybellinefitme.jpg" },
    ],
    category: "Beauty Products",
    seller: "Maybelline",
    stock: 40,
    numOfReviews: 19,
    reviews: [],
  },
  {
    name: "Samsung Galaxy Buds Pro",
    price: 149.99,
    description: "Wireless earbuds with noise cancellation.",
    ratings: 4.5,
    images: [
      { public_id: "shopit/products/demo/galaxybudspro", url: "https://res.cloudinary.com/udemy-courses/image/upload/v1689961861/shopit/products/demo/galaxybudspro.jpg" },
    ],
    category: "Electronics",
    seller: "Samsung",
    stock: 18,
    numOfReviews: 14,
    reviews: [],
  },
]